name: Test Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build coverage report
        env:
          CI: true
        run: |
          yarn
          yarn test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        env:
          COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
